name: Clumps
version: '4.0'
main: net.abhinav.clumps.Clumps
api-version: '1.21'
load: STARTUP
description: A plugin that merges XP orbs and instantly absorbs them when players are nearby to reduce lag.
authors: [ Abhinav VS ]
commands:
  clumps:
    description: Modify Clumps plugin settings
    usage: /<command> <set-<option>> <value> | /<command> showconfig
    permission: clumps.use
    permission-message: "You don't have permission to use this command."
    subcommands:
      showconfig:
        description: Show the current configuration settings
        usage: /clumps showconfig
        permission: clumps.admin
permissions:
  clumps.use:
    description: Allows access to modify the Clumps plugin settings
    default: op
  clumps.admin:
    description: Allows full access to modify Clumps plugin settings and show the config
    default: op
